SmartERP/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from SmartERP import api_urls

urlpatterns = [
    path('erp/admin/', admin.site.urls),
    # path('erp/category/', include('category.urls'), name='category'),
    path('erp/company/', include('company.urls'), name='company'),
    path('erp/customer/', include('customer.urls'), name='customer'),
    path('erp/document/', include('document.urls'), name='document'),
    path('erp/user/', include('erp_user.urls'), name='user'),
    path('erp/finance/', include('finance.urls'), name='finance'),
    path('erp/order/', include('order.urls'), name='order'),
    path('erp/price/', include('price.urls'), name='price'),
    path('erp/product/', include('product.urls'), name='product'),
    path('erp/reference/', include('reference.urls'), name='reference'),
    path('erp/unit/', include('unit.urls'), name='unit'),
    path('erp/wh/', include('warehouse.urls'), name='warehouse'),
    path('erp/dashboard/', include('dashboard.urls'), name='dashboard'),
    path('', include(api_urls), name='api'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/api/urls.py
from django.urls import path, include
from rest_framework import routers

from customer.api.views import CustomerViewSet

app_name = 'api_customer'

router = routers.DefaultRouter()

router.register('', CustomerViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

customer/urls.py
from django.urls import path

from customer.views import CustomerListView, CustomerAddView, CustomerUpdateView, \
    CustomerGroupListView, CustomerGroupAddView, CustomerGroupUpdateView

app_name = 'customer'

urlpatterns = [
    path('group/', CustomerGroupListView.as_view(), name='group_list'),
    path('group/<int:pk>/', CustomerGroupUpdateView.as_view(), name='group_edit'),
    path('group/add/', CustomerGroupAddView.as_view(), name='group_add'),

    path('', CustomerListView.as_view(), name='list'),
    path('<int:pk>/', CustomerUpdateView.as_view(), name='edit'),
    path('add/', CustomerAddView.as_view(), name='add'),
]

unit/urls.py
from django.urls import path

from unit.views import UnitListView, UnitAddView, UnitUpdateView, CaseListView, CaseAddView, CaseUpdateView

app_name = 'unit'

urlpatterns = [
    path('', UnitListView.as_view(), name='list'),
    path('add/', UnitAddView.as_view(), name='add'),
    path('<int:pk>/', UnitUpdateView.as_view(), name='edit'),

    path('box/', CaseListView.as_view(), name='case_list'),
    path('box/add/', CaseAddView.as_view(), name='case_add'),
    path('box/<int:pk>/', CaseUpdateView.as_view(), name='case_edit'),
]

customer/models.py
from django.db import models

from category.models import Category


class CustomerGroup(Category):
    pass


class Customer(models.Model):
    name = models.CharField(max_length=640)
    short_name = models.CharField(max_length=255, unique=True, null=True, blank=True)
    code = models.CharField(max_length=255, null=True, blank=True)
    user = models.OneToOneField('erp_user.User', on_delete=models.PROTECT, null=True, related_name='customer')
    group = models.CharField(max_length=960, null=True, blank=True)
    info = models.OneToOneField('document.Info', on_delete=models.PROTECT, null=True, blank=True,
                                related_name='owner_customer')
    document = models.OneToOneField('document.Document', on_delete=models.PROTECT, null=True, blank=True,
                                    related_name='owner_customer')
    created_date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} {self.user.get_full_name() if self.user else ""}'

customer/forms.py
from django import forms

from customer.models import Customer, CustomerGroup


class CustomerGroupForm(forms.ModelForm):
    class Meta:
        model = CustomerGroup
        fields = '__all__'


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

customer/api/views.py
from rest_framework import viewsets

from customer.api.serializers import CustomerSerializer
from customer.models import Customer


class CustomerViewSet(viewsets.ModelViewSet):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializer

customer/views.py
from django.urls import reverse_lazy, resolve
from django.views.generic import ListView, CreateView, UpdateView

from customer.forms import CustomerForm, CustomerGroupForm
from customer.models import Customer, CustomerGroup


class CustomerGroupListView(ListView):
    model = CustomerGroup


class CustomerGroupAddView(CreateView):
    model = CustomerGroup
    form_class = CustomerGroupForm
    success_url = reverse_lazy('customer:group_list')


class CustomerGroupUpdateView(UpdateView):
    model = CustomerGroup
    form_class = CustomerGroupForm
    success_url = reverse_lazy('customer:group_list')


class CustomerListView(ListView):
    model = Customer


class CustomerAddView(CreateView):
    model = Customer
    form_class = CustomerForm
    success_url = reverse_lazy('customer:list')


class CustomerUpdateView(UpdateView):
    model = Customer
    form_class = CustomerForm
    success_url = reverse_lazy('customer:list')

templates/customer/customer_form.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Add customer</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-primary btn-group-vertical save_top">Save</a>
            <a class="btn btn-default btn-default btn-group-vertical" href="{% url 'customer:list' %}">Close</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <form action="" method="post" class="form-group">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Save" hidden class="save_bottom">
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

templates/customer/customer_list.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Customers</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-success" href="{% url 'customer:add' %}">Add</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <table class="table table-hover table-striped table-bordered">
          <thead>
          <tr>
            <th>
              <input type="checkbox" id="selectAll"/>
            </th>
            <th scope="col">Code</th>
            <th scope="col">Name</th>
            <th scope="col">User</th>
            <th scope="col">Category</th>
            <th scope="col">Group</th>
            <th scope="col">Status</th>
          </tr>
          </thead>
          <tbody>
          {% for customer in customer_list %}
            <tr class="click-row" data-href="{% url 'customer:edit' customer.id %}">
              <td>
                <input type="checkbox" id="{{ product.id }}"/>
              </td>
              <td>{{ customer.code|default_if_none:"" }}</td>
              <td>{{ customer.name }}</td>
              <td>{{ customer.user|default_if_none:"" }}</td>
              <td>{{ customer.category|default_if_none:"" }}</td>
              <td>{{ customer.group|default_if_none:"" }}</td>
              <td>{% if customer.is_active %}Active{% else %}Inactive{% endif %}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}

templates/customer/customergroup_form.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Add customer</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-primary btn-group-vertical save_top">Save</a>
            <a class="btn btn-default btn-default btn-group-vertical" href="{% url 'customer:group_list' %}">Close</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <form action="" method="post" class="form-group">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Save" hidden class="save_bottom">
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

templates/customer/customergroup_list.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Customer groups</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-success" href="{% url 'customer:group_add' %}">Add</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <table class="table table-hover table-striped table-bordered">
          <thead>
          <tr>
            <th>
              <input type="checkbox" id="selectAll"/>
            </th>
            <th scope="col">id</th>
            <th scope="col">Code</th>
            <th scope="col">Name</th>
            <th scope="col">Number</th>
            <th scope="col">Status</th>
          </tr>
          </thead>
          <tbody>
          {% for group in customergroup_list %}
            <tr class="click-row" data-href="{% url 'customer:group_edit' group.id %}">
              <td>
                <input type="checkbox" id="{{ product.id }}"/>
              </td>
              <td>{{ group.id }}</td>
              <td>{{ group.code }}</td>
              <td>{{ group.name }}</td>
              <td>{{ group.number|default_if_none:"" }}</td>
              <td>{% if group.is_active %}Active{% else %}Inactive{% endif %}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}