SmartERP/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from SmartERP import api_urls

urlpatterns = [
    path('erp/admin/', admin.site.urls),
    # path('erp/category/', include('category.urls'), name='category'),
    path('erp/company/', include('company.urls'), name='company'),
    path('erp/customer/', include('customer.urls'), name='customer'),
    path('erp/document/', include('document.urls'), name='document'),
    path('erp/user/', include('erp_user.urls'), name='user'),
    path('erp/finance/', include('finance.urls'), name='finance'),
    path('erp/order/', include('order.urls'), name='order'),
    path('erp/price/', include('price.urls'), name='price'),
    path('erp/product/', include('product.urls'), name='product'),
    path('erp/reference/', include('reference.urls'), name='reference'),
    path('erp/unit/', include('unit.urls'), name='unit'),
    path('erp/wh/', include('warehouse.urls'), name='warehouse'),
    path('erp/dashboard/', include('dashboard.urls'), name='dashboard'),
    path('', include(api_urls), name='api'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/api/urls.py
from django.urls import path, include
from rest_framework import routers

from product.api.views import ProductViewSet

app_name = 'api_product'

router = routers.DefaultRouter()

router.register('', ProductViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

product/urls.py
from django.urls import path

from product.views import ProductListView, ProductAddView, ProductUpdateView, \
    ProductGroupListView, ProductGroupAddView, ProductGroupUpdateView, ProductGroupDeleteView, \
    ProductSubGroupListView, ProductSubGroupAddView, ProductSubGroupUpdateView, ProductSubGroupDeleteView

app_name = 'product'

urlpatterns = [
    path('group/', ProductGroupListView.as_view(), name='group_list'),
    path('group/<int:pk>/', ProductGroupUpdateView.as_view(), name='group_edit'),
    path('group/<int:pk>/del/', ProductGroupDeleteView.as_view(), name='group_delete'),
    path('group/add/', ProductGroupAddView.as_view(), name='group_add'),

    path('group/<int:pk>/sub/', ProductSubGroupListView.as_view(), name='group_sub_list'),
    path('group/sub/<int:pk>/', ProductSubGroupUpdateView.as_view(), name='group_sub_edit'),
    path('group/sub/<int:pk>/del/', ProductSubGroupDeleteView.as_view(), name='group_sub_delete'),
    path('group/<int:pk>/sub/add/', ProductSubGroupAddView.as_view(), name='group_sub_add'),

    path('', ProductListView.as_view(), name='list'),
    path('<int:pk>/', ProductUpdateView.as_view(), name='edit'),
    path('add/', ProductAddView.as_view(), name='add'),
]

unit/urls.py
from django.urls import path

from unit.views import UnitListView, UnitAddView, UnitUpdateView, CaseListView, CaseAddView, CaseUpdateView

app_name = 'unit'

urlpatterns = [
    path('', UnitListView.as_view(), name='list'),
    path('add/', UnitAddView.as_view(), name='add'),
    path('<int:pk>/', UnitUpdateView.as_view(), name='edit'),

    path('box/', CaseListView.as_view(), name='case_list'),
    path('box/add/', CaseAddView.as_view(), name='case_add'),
    path('box/<int:pk>/', CaseUpdateView.as_view(), name='case_edit'),
]

product/models.py
from django.db import models

from category.models import Category, SubCategory


class ProductGroup(Category):
    pass


class ProductSubGroup(SubCategory):
    group = models.ForeignKey('ProductGroup', on_delete=models.PROTECT, related_name='subtypes')


class Product(models.Model):
    name = models.CharField(max_length=255, unique=True)
    short_name = models.CharField(max_length=255, unique=True, null=True, blank=True)
    code = models.CharField(max_length=255, unique=True, null=True, blank=True)
    barcode = models.CharField(max_length=255, null=True, blank=True)
    weight_brutto = models.FloatField(null=True, blank=True)
    weight_netto = models.FloatField(null=True, blank=True)
    volume = models.FloatField(null=True, blank=True)
    group = models.CharField(max_length=960, null=True, blank=True)
    manufacturer = models.ForeignKey('reference.Manufacturer', on_delete=models.PROTECT, related_name='products',
                                     null=True, blank=True)
    country = models.ForeignKey('reference.Country', on_delete=models.PROTECT, related_name='products', null=True,
                                blank=True)
    measure = models.ForeignKey('unit.Unit', on_delete=models.PROTECT, related_name='products')
    box_type = models.ForeignKey('unit.Case', on_delete=models.PROTECT, related_name='products', null=True, blank=True)
    box_quantity = models.IntegerField(null=True, blank=True)
    order_number = models.IntegerField(null=True, blank=True)
    document = models.OneToOneField('document.Document', on_delete=models.PROTECT, null=True, blank=True)
    product_tares = models.ManyToManyField('self', blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

product/forms.py
from django import forms

from product.models import Product, ProductGroup, ProductSubGroup


class ProductGroupForm(forms.ModelForm):
    class Meta:
        model = ProductGroup
        fields = '__all__'


class ProductSubGroupForm(forms.ModelForm):
    class Meta:
        model = ProductSubGroup
        fields = '__all__'


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

product/api/views.py
from rest_framework import viewsets

from product.api.serializers import ProductSerializer
from product.models import Product


class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

product/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from product.forms import ProductForm, ProductGroupForm, ProductSubGroupForm
from product.models import Product, ProductGroup, ProductSubGroup


class ProductGroupListView(ListView):
    model = ProductGroup


class ProductGroupAddView(CreateView):
    model = ProductGroup
    form_class = ProductGroupForm
    success_url = reverse_lazy('product:group_list')


class ProductGroupUpdateView(UpdateView):
    model = ProductGroup
    form_class = ProductGroupForm
    success_url = reverse_lazy('product:group_list')


class ProductGroupDeleteView(DeleteView):
    model = ProductGroup
    success_url = reverse_lazy('product:group_list')


class ProductSubGroupListView(ListView):
    model = ProductSubGroup

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['subgroup_list'] = ProductSubGroup.objects.filter(group_id=self.kwargs.get('pk'))
        return context


class ProductSubGroupAddView(CreateView):
    model = ProductSubGroup
    form_class = ProductSubGroupForm
    success_url = reverse_lazy('product:group_sub_list')


class ProductSubGroupUpdateView(UpdateView):
    model = ProductSubGroup
    form_class = ProductSubGroupForm
    success_url = reverse_lazy('product:group_sub_list')


class ProductSubGroupDeleteView(DeleteView):
    model = ProductSubGroup
    success_url = reverse_lazy('product:group_sub_list')


class ProductListView(ListView):
    model = Product


class ProductAddView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('product:list')


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('product:list')

templates/product/product_form.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Product</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-primary btn-group-vertical save_top">Save</a>
            <a class="btn btn-default btn-default btn-group-vertical" href="{% url 'product:list' %}">Close</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <form action="" method="post" class="form-group-lg">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Save" class="save_bottom" hidden>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

templates/product/product_list.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Products</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-success" href="{% url 'product:add' %}">Add</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <table class="table table-hover table-striped table-bordered">
          <thead>
          <tr>
            <th>
              <input type="checkbox" id="selectAll"/>
            </th>
            <th scope="col">Code</th>
            <th scope="col">Name</th>
            <th scope="col">Manufacturer</th>
            <th scope="col">Country</th>
            <th scope="col">Measure</th>
            <th scope="col">Case type</th>
            <th scope="col">Box quantity</th>
            <th scope="col">Group</th>
            <th scope="col">Status</th>
          </tr>
          </thead>
          <tbody>
          {% for product in product_list %}
            <tr class="click-row" data-href="{% url 'product:edit' product.id %}">
              <td>
                <input type="checkbox" id="{{ product.id }}"/>
              </td>
              <td>{{ product.code|default_if_none:"" }}</td>
              <td>{{ product.name }}</td>
              <td>{{ product.manufacturer|default_if_none:"" }}</td>
              <td>{{ product.country|default_if_none:"" }}</td>
              <td>{{ product.measure }}</td>
              <td>{{ product.box_type|default_if_none:"" }}</td>
              <td>{{ product.box_quantity|default_if_none:"" }}</td>
              <td>{{ product.group|default_if_none:"" }}</td>
              <td>{% if product.is_active %}Active{% else %}Inactive{% endif %}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}

templates/product/productgroup_form.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Product</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-primary btn-group-vertical save_top">Save</a>
            <a class="btn btn-default btn-default btn-group-vertical" href="{% url 'product:group_list' %}">Close</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <form action="" method="post" class="form-group-lg">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Save" class="save_bottom" hidden>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

templates/product/productgroup_list.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Product Groups</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-success" href="{% url 'product:group_add' %}">Add</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <table class="table table-hover table-striped table-bordered">
          <thead>
          <tr>
            <th>
              <input type="checkbox" id="selectAll"/>
            </th>
            <th scope="col">id</th>
            <th scope="col">Name</th>
            <th scope="col">Status</th>
          </tr>
          </thead>
          <tbody>
          {% for group in productgroup_list %}
            <tr class="click-row" data-href="{% url 'product:group_edit' group.id %}" data-toggle="collapse"
                data-target="#collapse_{{ group.id }}">
              <td>
                <input type="checkbox" id="{{ product.id }}"/>
              </td>
              <td>{{ group.id }}</td>
              <td>{{ group.name }}</td>
              <td>{% if group.is_active %}Active{% else %}Inactive{% endif %}</td>
            </tr>
            <tr>
              <td id="collapse_{{ group.id }}" class="collapse out" colspan="5">

                <a href="{% url 'product:group_edit' group.id %}" class="btn btn-outline-dark btn-sm" role="button">
                  Edit
                </a>
                <a href="{% url 'product:group_delete' group.id %}" class="btn btn-outline-dark btn-sm"
                   role="button" data-toggle="modal" data-target="#deleteConfirmModal">
                  Delete
                </a>
                <a href="{% url 'product:group_sub_list' group.id %}" class="btn btn-outline-dark btn-sm" role="button">
                  Subtypes
                </a>
              </td>
            </tr>
            <!-- Modal -->
            <div class="modal fade" id="deleteConfirmModal" tabindex="-1" role="dialog"
                 aria-labelledby="deleteConfirmModalLabel"
                 aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">

                  <div class="modal-body">
                    Are you sure?
                  </div>
                  <div class="modal-footer">
                    <form method="POST" action="{% url 'product:group_delete' group.id %}">
                      {% csrf_token %}
                      <input type="submit" class="btn btn-danger" value="Delete">
                    </form>
                    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
            <!-- Modal end -->
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}

templates/product/productsubgroup_form.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Product</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-primary btn-group-vertical save_top">Save</a>
            <a class="btn btn-default btn-default btn-group-vertical" href="{% url 'product:group_list' %}">Close</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <form action="" method="post" class="form-group-lg">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Save" class="save_bottom" hidden>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

templates/product/productsubgroup_list.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Product Groups</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-success" href="{% url 'product:group_sub_add' '1' %}">Add</a>
            <a class="btn btn-success" href="{% url 'product:group_list' %}">Close</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <table class="table table-hover table-striped table-bordered">
          <thead>
          <tr>
            <th><input type="checkbox" id="selectall"/></th>
            <th scope="col">id</th>
            <th scope="col">Code</th>
            <th scope="col">Name</th>
            <th scope="col">Group</th>
            <th scope="col">Number</th>
            <th scope="col">Status</th>
          </tr>
          </thead>
          <tbody>
          {% for group in subgroup_list %}
            <tr class="click-row" data-href="{% url 'product:group_sub_edit' group.id %}" data-toggle="collapse"
                data-target="#collapse_{{ group.id }}">
              <td><input type="checkbox" class="singlechkbox" name="username" value="{{ group.id }}"/></td>
              <td class="group_id" data-val="{{ group.id }}">{{ group.id }}</td>
              <td>{{ group.code|default_if_none:"" }}</td>
              <td>{{ group.name }}</td>
              <td>{{ group.group }}</td>
              <td>{{ group.number|default_if_none:"" }}</td>
              <td>{% if group.is_active %}Active{% else %}Inactive{% endif %}</td>
            </tr>
            <tr>
              <td id="collapse_{{ group.id }}" class="collapse out" colspan="5">

                <a href="{% url 'product:group_sub_edit' group.id %}" class="btn btn-outline-dark btn-sm" role="button">
                  Edit
                </a>
                <a href="{% url 'product:group_delete' group.id %}" class="btn btn-outline-dark btn-sm"
                   role="button" data-toggle="modal" data-target="#deleteConfirmModal">
                  Delete
                </a>
                <a href="" class="btn btn-outline-dark btn-sm" role="button">
                  Products
                </a>
              </td>
            </tr>
            <!-- Modal -->
            <div class="modal fade" id="deleteConfirmModal" tabindex="-1" role="dialog"
                 aria-labelledby="deleteConfirmModalLabel"
                 aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">

                  <div class="modal-body">
                    Are you sure?
                  </div>
                  <div class="modal-footer">
                    <form method="POST" action="{% url 'product:group_delete' group.id %}">
                      {% csrf_token %}
                      <input type="submit" class="btn btn-danger" value="Delete">
                    </form>
                    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
            <!-- Modal end -->
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}