SmartERP/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from SmartERP import api_urls

urlpatterns = [
    path('erp/admin/', admin.site.urls),
    # path('erp/category/', include('category.urls'), name='category'),
    path('erp/company/', include('company.urls'), name='company'),
    path('erp/customer/', include('customer.urls'), name='customer'),
    path('erp/document/', include('document.urls'), name='document'),
    path('erp/user/', include('erp_user.urls'), name='user'),
    path('erp/finance/', include('finance.urls'), name='finance'),
    path('erp/order/', include('order.urls'), name='order'),
    path('erp/price/', include('price.urls'), name='price'),
    path('erp/product/', include('product.urls'), name='product'),
    path('erp/reference/', include('reference.urls'), name='reference'),
    path('erp/unit/', include('unit.urls'), name='unit'),
    path('erp/wh/', include('warehouse.urls'), name='warehouse'),
    path('erp/dashboard/', include('dashboard.urls'), name='dashboard'),
    path('', include(api_urls), name='api'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unit/urls.py
from django.urls import path

from unit.views import UnitListView, UnitAddView, UnitUpdateView, CaseListView, CaseAddView, CaseUpdateView

app_name = 'unit'

urlpatterns = [
    path('', UnitListView.as_view(), name='list'),
    path('add/', UnitAddView.as_view(), name='add'),
    path('<int:pk>/', UnitUpdateView.as_view(), name='edit'),

    path('box/', CaseListView.as_view(), name='case_list'),
    path('box/add/', CaseAddView.as_view(), name='case_add'),
    path('box/<int:pk>/', CaseUpdateView.as_view(), name='case_edit'),
]

warehouse/api/urls.py
from django.urls import path, include
from rest_framework import routers

from warehouse.api.views import WarehouseViewSet

router = routers.DefaultRouter()

router.register('', WarehouseViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

warehouse/urls.py
from django.urls import path

from warehouse.views import *

app_name = 'warehouse'

urlpatterns = [
    path('', WarehouseListView.as_view(), name='list'),
    path('<int:pk>/', WarehouseUpdateView.as_view(), name='edit'),
    path('add/', WarehouseAddView.as_view(), name='add'),

    path('stock/', StockListView.as_view(), name='stock_list'),
    path('stock/<str:details>/', StockListView.as_view(), name='stock_list_details'),

    path('input/', ProductTransactionListView.as_view(), name='stock_input_list'),
    path('input/add/', ProductTransactionAddView.as_view(), name='stock_input_add'),
    path('input/<int:pk>/', ProductTransactionEditView.as_view(), name='stock_input_edit'),

    # path('input/', WarehouseInputListView.as_view(), name='input_list'),
    # path('input/<int:pk>/', WarehouseInputUpdateView.as_view(), name='input_edit'),
    # path('input/add/', WarehouseInputAddView.as_view(), name='input_add'),

    # path('balance/', WarehouseBalanceListView.as_view(), name='balance'),
]

warehouse/models.py
from django.db import models
from django.db.models import F
from django.utils import timezone

from tools.config import CONSTANTS


class Warehouse(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=255, null=True, blank=True)
    number = models.IntegerField(null=True, blank=True)
    accountable = models.ForeignKey('erp_user.User', on_delete=models.PROTECT)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Stock(models.Model):
    product = models.ForeignKey('product.Product', on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(decimal_places=4, max_digits=20)
    expire_date = models.DateField(null=True, blank=True)
    warehouse = models.ForeignKey('Warehouse', on_delete=models.PROTECT, related_name='stocks')
    transaction = models.ForeignKey('ProductTransaction', on_delete=models.CASCADE, related_name='stocks')
    status = models.CharField(max_length=255, choices=CONSTANTS.WAREHOUSE.STOCK.STATUS.CHOICES)
    timestamp = models.DateTimeField(default=timezone.now)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def increase_stock(self, quantity: int, commit: bool = True):
        self.quantity = F("quantity") + quantity
        if commit:
            self.save(update_fields=["quantity"])

    def decrease_stock(self, quantity: int, commit: bool = True):
        self.quantity = F("quantity") - quantity
        if commit:
            self.save(update_fields=["quantity"])

    def __str__(self):
        return f'{self.product.name} - {self.quantity}'


class ProductTransaction(models.Model):
    number = models.PositiveIntegerField(null=True, blank=True)
    transaction_type = models.CharField(max_length=255, choices=CONSTANTS.WAREHOUSE.TRANSACTION.TYPE.CHOICES)
    note = models.CharField(max_length=640, null=True, blank=True)
    warehouse = models.ForeignKey('Warehouse', on_delete=models.PROTECT, related_name='transactions')
    timestamp = models.DateTimeField(default=timezone.now)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        pk = self.pk
        super().save(*args, **kwargs)
        # print('pk\n', pk)
        # print('instance\n', self.__dict__)
        if self.transaction_type in ['NEW', 'ARRIVED']:
            for item in self.items.all():
                # print('item\n', item.__dict__)
                self.stocks.create(product=item.product, quantity=item.quantity,
                                   price=item.price, warehouse=self.warehouse)


class TransactionItem(models.Model):
    product = models.ForeignKey('product.Product', on_delete=models.CASCADE, related_name='transactions')
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(decimal_places=4, max_digits=20)
    transaction = models.ForeignKey('ProductTransaction', on_delete=models.CASCADE, related_name='items')

warehouse/forms.py
from django import forms
from django.forms import formset_factory

from warehouse.models import *


class WarehouseForm(forms.ModelForm):
    class Meta:
        model = Warehouse
        fields = '__all__'


class StockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = '__all__'


# StockFormSet = formset_factory(StockForm)


class ProductTransactionForm(forms.ModelForm):
    class Meta:
        model = ProductTransaction
        fields = '__all__'


class TransactionItemForm(forms.ModelForm):
    class Meta:
        model = TransactionItem
        fields = '__all__'


ProductTransactionFormset = forms.inlineformset_factory(ProductTransaction, TransactionItem,
                                                        fields=['product', 'price', 'quantity'],
                                                        form=TransactionItemForm,
                                                        extra=1)

# class WarehouseBalanceForm(forms.ModelForm):
#     class Meta:
#         model = Balance
#         fields = '__all__'

warehouse/api/views.py
from rest_framework import viewsets

from warehouse.api.serializers import WarehouseSerializer
from warehouse.models import Warehouse


class WarehouseViewSet(viewsets.ModelViewSet):
    queryset = Warehouse.objects.all()
    serializer_class = WarehouseSerializer

warehouse/views.py
from django.db import transaction
from django.db.models import Sum, Q
from django.urls import reverse_lazy, resolve
from django.views.generic import ListView, CreateView, UpdateView

from warehouse.forms import *
from warehouse.models import *


class WarehouseListView(ListView):
    model = Warehouse


class WarehouseAddView(CreateView):
    model = Warehouse
    form_class = WarehouseForm
    success_url = reverse_lazy('warehouse:list')


class WarehouseUpdateView(UpdateView):
    model = Warehouse
    form_class = WarehouseForm
    success_url = reverse_lazy('warehouse:list')


class StockListView(ListView):
    model = Stock

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        details = self.kwargs.get('details')
        context['details_url'] = resolve(self.request.path_info).url_name == 'stock_list_details'
        if details:
            context['stock_list'] = Stock.objects.values('product__name').annotate(quantities=Sum('quantity'),
                                                                                   product=F('product__name'),
                                                                                   booked=Sum('quantity', filter=Q(
                                                                                       status='BOOKED')),
                                                                                   warehouse=F('warehouse__name'))
        else:
            context['stock_list'] = Stock.objects.values('product__name').annotate(quantities=Sum('quantity'),
                                                                                   booked=Sum('quantity', filter=Q(
                                                                                       status='BOOKED')),
                                                                                   product=F('product__name'))
        print('context:\n', context['stock_list'])
        return context


class ProductTransactionListView(ListView):
    model = ProductTransaction


class ProductTransactionAddView(CreateView):
    model = ProductTransaction
    fields = '__all__'
    # form_class = ProductTransactionFormset
    success_url = reverse_lazy('warehouse:stock_input_list')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['transactions'] = ProductTransactionFormset(self.request.POST)
        else:
            data['transactions'] = ProductTransactionFormset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        trans = context['transactions']
        with transaction.atomic():
            self.object = form.save()

            if trans.is_valid():
                trans.instance = self.object
                trans.save()
        return super().form_valid(form)


class ProductTransactionEditView(UpdateView):
    model = ProductTransaction
    fields = '__all__'
    # form_class = ProductTransactionForm
    success_url = reverse_lazy('warehouse:stock_input_list')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['transactions'] = ProductTransactionFormset(self.request.POST, instance=self.object)
        else:
            data['transactions'] = ProductTransactionFormset(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        transactions = context['transactions']
        with transaction.atomic():
            self.object = form.save()

            if transactions.is_valid():
                transactions.instance = self.object
                transactions.save()
        return super().form_valid(form)

# class StockAddView(CreateView):
#     model = Stock
#     fields = '__all__'
#     success_url = reverse_lazy('warehouse:stock_list')
#
#     def get_context_data(self, **kwargs):
#         data = super().get_context_data(**kwargs)
#         if self.request.POST:
#             data['inputs'] = StockFormSet(self.request.POST)
#         else:
#             data['inputs'] = StockFormSet()
#         return data
#
#     def form_valid(self, form):
#         context = self.get_context_data()
#         inputs = context['inputs']
#         with transaction.atomic():
#             self.object = form.save()
#
#             if inputs.is_valid():
#                 inputs.instance = self.object
#                 inputs.save()
#         return super().form_valid(form)


# class StockUpdateView(CreateView):
#     model = Stock
#     form_class = StockForm
#     success_url = reverse_lazy('warehouse:stock_list')

# class WarehouseInputAddView(CreateView):
#     model = WarehouseInput
#     fields = '__all__'
#     success_url = reverse_lazy('warehouse:input_list')
#
#     def get_context_data(self, **kwargs):
#         data = super().get_context_data(**kwargs)
#         if self.request.POST:
#             data['inputs'] = InputProductFormset(self.request.POST)
#         else:
#             data['inputs'] = InputProductFormset()
#         return data
#
#     def form_valid(self, form):
#         context = self.get_context_data()
#         inputs = context['inputs']
#         with transaction.atomic():
#             self.object = form.save()
#
#             if inputs.is_valid():
#                 inputs.instance = self.object
#                 inputs.save()
#         return super().form_valid(form)
#
#
# class WarehouseInputUpdateView(UpdateView):
#     model = WarehouseInput
#     fields = '__all__'
#     success_url = reverse_lazy('warehouse:input_list')
#
#     def get_context_data(self, **kwargs):
#         data = super().get_context_data(**kwargs)
#         if self.request.POST:
#             data['inputs'] = InputProductFormset(self.request.POST, instance=self.object)
#         else:
#             data['inputs'] = InputProductFormset(instance=self.object)
#         return data
#
#     def form_valid(self, form):
#         context = self.get_context_data()
#         inputs = context['inputs']
#         with transaction.atomic():
#             self.object = form.save()
#
#             if inputs.is_valid():
#                 inputs.instance = self.object
#                 inputs.save()
#         return super().form_valid(form)
#
#
# class WarehouseBalanceListView(ListView):
#     model = Balance
#
#     def get_context_data(self, *args, object_list=None, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['balance_list'] = Balance.objects.all()
#         return context

templates/warehouse/balance_list.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Remains</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-success" href="#">123</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <table class="table table-hover table-striped table-bordered">
          <thead>
          <tr>
            <th scope="col">Product</th>
            <th scope="col">Остаток</th>
            <th scope="col">Бронь</th>
            <th scope="col">Доступно</th>
          </tr>
          </thead>
          <tbody>
          {% for remain in balance_list %}
            <tr class="click-row" data-href="{% url 'warehouse:edit' remain.id %}">
              <td>{{ remain.product }}</td>
              <td>{{ remain.amount }}</td>
              <td>{{ remain.warehouse }}</td>
              <td>{{ remain.created_date }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}

templates/warehouse/producttransaction_form.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Product</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-primary btn-group-vertical save_top">Save</a>
            <a class="btn btn-default btn-default btn-group-vertical" href="{% url 'warehouse:stock_input_list' %}">Close</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <form action="" method="post" class="form-group-lg">
          {% csrf_token %}
          {{ form.as_p }}
          <table class="table table-hover table-striped table-bordered">
            {{ transactions.management_form }}

            {% for form in transactions.forms %}
              {% if forloop.first %}
                <thead>
                <tr>
                  {% for field in form.visible_fields %}
                    <th>{{ field.label|capfirst }}</th>
                  {% endfor %}
                </tr>
                </thead>
              {% endif %}
              <tr class="{% cycle row1 row2 %} formset_row">
                {% for field in form.visible_fields %}
                  <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                      {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                      {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field }}
                  </td>
                {% endfor %}
              </tr>
            {% endfor %}
          </table>
          <input type="submit" value="Save" class="save_bottom" hidden>
        </form>
      </div>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.min.js"></script>
  <script type="text/javascript">
      $('.formset_row').formset({
          addText: 'Add',
          deleteText: 'X',
          prefix: 'items'
      });
  </script>
{% endblock content %}

templates/warehouse/producttransaction_list.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Warehouse Inputs</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-success" href="{% url 'warehouse:stock_input_add' %}">Add</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <table class="table table-hover table-striped table-bordered">
          <thead>
          <tr>
            <th>
              <input type="checkbox" id="selectAll"/>
            </th>
            <th scope="col">id</th>
            <th scope="col">№</th>
            <th scope="col">Warehouse</th>
            <th scope="col">Created</th>
            <th scope="col">Note</th>
            <th scope="col">Status</th>
          </tr>
          </thead>
          <tbody>
          {% for trans in producttransaction_list %}
            <tr class="click-row" data-href="{% url 'warehouse:stock_input_edit' trans.id %}">
              <td>
                <input type="checkbox" id="{{ input.id }}"/>
              </td>
              <td>{{ trans.id }}</td>
              <td>{{ trans.number }}</td>
              <td>{{ trans.warehouse }}</td>
              <td>{{ trans.created_date }}</td>
              <td>{{ trans.note|default_if_none:"" }}</td>
              <td>{{ trans.status }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}

templates/warehouse/stock_form.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Product</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-primary btn-group-vertical save_top">Save</a>
            <a class="btn btn-default btn-default btn-group-vertical" href="{% url 'warehouse:stock_list' %}">Close</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <form action="" method="post" class="form-group-lg">
          {% csrf_token %}
          {% for form in forrmset %}
            {{ form.as_p }}
          {% endfor %}
          <table class="table table-hover table-striped table-bordered">
            {{ inputs.management_form }}

            {% for form in inputs.forms %}
              {% if forloop.first %}
                <thead>
                <tr>
                  {% for field in form.visible_fields %}
                    <th>{{ field.label|capfirst }}</th>
                  {% endfor %}
                </tr>
                </thead>
              {% endif %}
              <tr class="{% cycle row1 row2 %} formset_row">
                {% for field in form.visible_fields %}
                  <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                      {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                      {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field }}
                  </td>
                {% endfor %}
              </tr>
            {% endfor %}
          </table>
          <input type="submit" value="Save" class="save_bottom" hidden>
        </form>
      </div>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.min.js"></script>
  <script type="text/javascript">
      $('.formset_row').formset({
          addText: 'Add',
          deleteText: 'X',
          prefix: 'products'
      });
  </script>
{% endblock content %}

templates/warehouse/stock_list.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Remains</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-success" href="{% url 'warehouse:stock_list_details' 'details' %}">Details</a>
            {% if details_url %}
              <a class="btn btn-success" href="{% url 'warehouse:stock_list' %}">Close</a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="card card-body">
        <table class="table table-hover table-striped table-bordered">
          <thead>
          <tr>
            {% if details_url %}
              <th scope="col">Warehouse</th>
            {% endif %}
            <th scope="col">Product</th>
            <th scope="col">Остаток</th>
            <th scope="col">Бронь</th>
            <th scope="col">Доступно</th>
          </tr>
          </thead>
          <tbody>
          {% for remain in stock_list %}
            <tr class="click-row" data-href="#">
              {% if details_url %}
                <td>{{ remain.warehouse }}</td>
              {% endif %}
              <td>{{ remain.product__name }}</td>
              <td>{{ remain.quantities }}</td>
              <td>{{ remain.booked|default_if_none:"" }}</td>
              <td> {% if remain.booked %}
                {{ remain.quantities|sub:remain.booked }}{% else %}
                {{ remain.quantities }}{% endif %}
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}

templates/warehouse/warehouse_form.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Product</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-primary btn-group-vertical save_top">Save</a>
            <a class="btn btn-default btn-default btn-group-vertical" href="{% url 'warehouse:list' %}">Close</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <form action="" method="post" class="form-group-lg">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Save" class="save_bottom" hidden>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

templates/warehouse/warehouse_list.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Warehouses</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-success" href="{% url 'warehouse:add' %}">Add</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <table class="table table-hover table-striped table-bordered">
          <thead>
          <tr>
            <th>
              <input type="checkbox" id="selectAll"/>
            </th>
            <th scope="col">id</th>
            <th scope="col">Code</th>
            <th scope="col">Name</th>
            <th scope="col">Accountable</th>
            <th scope="col">Status</th>
          </tr>
          </thead>
          <tbody>
          {% for warehouse in warehouse_list %}
            <tr class="click-row" data-href="{% url 'warehouse:edit' warehouse.id %}">
              <td>
                <input type="checkbox" id="{{ warehouse.id }}"/>
              </td>
              <td>{{ warehouse.id }}</td>
              <td>{{ warehouse.code|default_if_none:"" }}</td>
              <td>{{ warehouse.name }}</td>
              <td>{{ warehouse.accountable }}</td>
              <td>{% if warehouse.is_active %}Active{% else %}Inactive{% endif %}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}

templates/warehouse/warehouseinput_form.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Product</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-primary btn-group-vertical save_top">Save</a>
            <a class="btn btn-default btn-default btn-group-vertical" href="{% url 'warehouse:input_list' %}">Close</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <form action="" method="post" class="form-group-lg">
          {% csrf_token %}
          {{ form.as_p }}
          <table class="table table-hover table-striped table-bordered">
            {{ inputs.management_form }}

            {% for form in inputs.forms %}
              {% if forloop.first %}
                <thead>
                <tr>
                  {% for field in form.visible_fields %}
                    <th>{{ field.label|capfirst }}</th>
                  {% endfor %}
                </tr>
                </thead>
              {% endif %}
              <tr class="{% cycle row1 row2 %} formset_row">
                {% for field in form.visible_fields %}
                  <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                      {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                      {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field }}
                  </td>
                {% endfor %}
              </tr>
            {% endfor %}
          </table>
          <input type="submit" value="Save" class="save_bottom" hidden>
        </form>
      </div>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.min.js"></script>
  <script type="text/javascript">
      $('.formset_row').formset({
          addText: 'Add',
          deleteText: 'X',
          prefix: 'products'
      });
  </script>
{% endblock content %}

templates/warehouse/warehouseinput_list.html
{% extends 'base.html' %}
{% block content %}
  <br>
  <div class="row">
    <div class="col-md">
      <div class="card card-body">
        <h6>Warehouse Inputs</h6>
        <div class="row">
          <div class="col-md-4">
            <a class="btn btn-success" href="{% url 'warehouse:input_add' %}">Add</a>
          </div>
        </div>
      </div>
      <div class="card card-body">
        <table class="table table-hover table-striped table-bordered">
          <thead>
          <tr>
            <th>
              <input type="checkbox" id="selectAll"/>
            </th>
            <th scope="col">id</th>
            <th scope="col">№</th>
            <th scope="col">Warehouse</th>
            <th scope="col">Created</th>
            <th scope="col">Note</th>
            <th scope="col">Status</th>
          </tr>
          </thead>
          <tbody>
          {% for input in warehouseinput_list %}
            <tr class="click-row" data-href="{% url 'warehouse:input_edit' input.id %}">
              <td>
                <input type="checkbox" id="{{ input.id }}"/>
              </td>
              <td>{{ input.id }}</td>
              <td>{{ input.number }}</td>
              <td>{{ input.warehouse }}</td>
              <td>{{ input.created_date }}</td>
              <td>{{ input.note|default_if_none:"" }}</td>
              <td>{{ input.status }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}