SmartERP/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from SmartERP import api_urls

urlpatterns = [
    path('erp/admin/', admin.site.urls),
    # path('erp/category/', include('category.urls'), name='category'),
    path('erp/company/', include('company.urls'), name='company'),
    path('erp/customer/', include('customer.urls'), name='customer'),
    path('erp/document/', include('document.urls'), name='document'),
    path('erp/user/', include('erp_user.urls'), name='user'),
    path('erp/finance/', include('finance.urls'), name='finance'),
    path('erp/order/', include('order.urls'), name='order'),
    path('erp/price/', include('price.urls'), name='price'),
    path('erp/product/', include('product.urls'), name='product'),
    path('erp/reference/', include('reference.urls'), name='reference'),
    path('erp/unit/', include('unit.urls'), name='unit'),
    path('erp/wh/', include('warehouse.urls'), name='warehouse'),
    path('erp/dashboard/', include('dashboard.urls'), name='dashboard'),
    path('', include(api_urls), name='api'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/api/urls.py
# from django.urls import path, include
# from rest_framework.routers import DefaultRouter
#
# from category.api.views import CategoryViewSet
#
# router = DefaultRouter()
#
# router.register('category', CategoryViewSet, basename='category')
#
# urlpatterns = [
#     path('', include(router.urls)),
# ]

category/urls.py
from django.urls import path

from category.views import CategoryListView, CategoryUpdateView, CategoryAddView

app_name = 'category'

urlpatterns = [
    # path('', CategoryListView.as_view(), name='list'),
    # path('<str:item>/list/', CategoryListView.as_view(), name='list'),
    # path('<int:pk>/sub/', CategoryListView.as_view(), name='child_list'),
    # path('<int:pk>/', CategoryUpdateView.as_view(), name='edit'),
    # path('add/', CategoryAddView.as_view(), name='add'),
]

company/api/urls.py
from django.urls import path

urlpatterns = [
    # path('', ),
]

company/urls.py
from django.urls import path

urlpatterns = [
    # path('', ),
]

customer/api/urls.py
from django.urls import path, include
from rest_framework import routers

from customer.api.views import CustomerViewSet

app_name = 'api_customer'

router = routers.DefaultRouter()

router.register('', CustomerViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

customer/urls.py
from django.urls import path

from customer.views import CustomerListView, CustomerAddView, CustomerUpdateView, \
    CustomerGroupListView, CustomerGroupAddView, CustomerGroupUpdateView

app_name = 'customer'

urlpatterns = [
    path('group/', CustomerGroupListView.as_view(), name='group_list'),
    path('group/<int:pk>/', CustomerGroupUpdateView.as_view(), name='group_edit'),
    path('group/add/', CustomerGroupAddView.as_view(), name='group_add'),

    path('', CustomerListView.as_view(), name='list'),
    path('<int:pk>/', CustomerUpdateView.as_view(), name='edit'),
    path('add/', CustomerAddView.as_view(), name='add'),
]

dashboard/urls.py
from django.urls import path

from dashboard.views import home

app_name = 'dashboard'

urlpatterns = [
    path('', home, name='dashboard'),
]

document/urls.py
from django.urls import path

urlpatterns = [
    # path('', ),
]

erp_user/urls.py
from django.urls import path

from erp_user.views import register_user, login_user, logout_user, user_page, account_settings

app_name = 'erp_user'

urlpatterns = [
    path('register/', register_user, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('account/', account_settings, name="account"),
    path('', user_page, name='user_page'),
]

finance/api/urls.py
from django.urls import path

urlpatterns = [
    # path('', ),
]

finance/urls.py
from django.urls import path

urlpatterns = [
    # path('', ),
]

order/api/urls.py
from django.urls import path

from order.views import order, create_order, update_order, delete_order

app_name = 'api_order'

urlpatterns = [
    path('', order, name='order_list'),
    path('<int:pk>/', update_order, name='order_detail'),
    path('add/<int:pk>/', create_order, name='create_order'),
    path('remove/<int:pk>/', delete_order, name='delete_order'),
]

order/urls.py
from django.urls import path

from order.views import order, create_order, update_order, delete_order

app_name = 'order'

urlpatterns = [
    path('', order, name='order_list'),
    path('<int:pk>/', update_order, name='order_detail'),
    path('add/<int:pk>/', create_order, name='create_order'),
    path('remove/<int:pk>/', delete_order, name='delete_order'),
]

price/api/urls.py
from django.urls import path

urlpatterns = [
    # path('', ),
]

price/urls.py
from django.urls import path

from price.views import PriceListView, PriceAddView, PriceUpdateView, CurrencyListView, CurrencyAddView, \
    CurrencyUpdateView

app_name = 'price'

urlpatterns = [
    path('', PriceListView.as_view(), name='list'),
    path('add/', PriceAddView.as_view(), name='add'),
    path('<int:pk>/', PriceUpdateView.as_view(), name='edit'),

    path('currency/', CurrencyListView.as_view(), name='currency_list'),
    path('currency/add/', CurrencyAddView.as_view(), name='currency_add'),
    path('currency/<int:pk>/', CurrencyUpdateView.as_view(), name='currency_edit'),
]

product/api/urls.py
from django.urls import path, include
from rest_framework import routers

from product.api.views import ProductViewSet

app_name = 'api_product'

router = routers.DefaultRouter()

router.register('', ProductViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

product/urls.py
from django.urls import path

from product.views import ProductListView, ProductAddView, ProductUpdateView, \
    ProductGroupListView, ProductGroupAddView, ProductGroupUpdateView, ProductGroupDeleteView, \
    ProductSubGroupListView, ProductSubGroupAddView, ProductSubGroupUpdateView, ProductSubGroupDeleteView

app_name = 'product'

urlpatterns = [
    path('group/', ProductGroupListView.as_view(), name='group_list'),
    path('group/<int:pk>/', ProductGroupUpdateView.as_view(), name='group_edit'),
    path('group/<int:pk>/del/', ProductGroupDeleteView.as_view(), name='group_delete'),
    path('group/add/', ProductGroupAddView.as_view(), name='group_add'),

    path('group/<int:pk>/sub/', ProductSubGroupListView.as_view(), name='group_sub_list'),
    path('group/sub/<int:pk>/', ProductSubGroupUpdateView.as_view(), name='group_sub_edit'),
    path('group/sub/<int:pk>/del/', ProductSubGroupDeleteView.as_view(), name='group_sub_delete'),
    path('group/<int:pk>/sub/add/', ProductSubGroupAddView.as_view(), name='group_sub_add'),

    path('', ProductListView.as_view(), name='list'),
    path('<int:pk>/', ProductUpdateView.as_view(), name='edit'),
    path('add/', ProductAddView.as_view(), name='add'),
]

reference/urls.py
from django.urls import path

urlpatterns = [
    # path('', ),
]

unit/api/urls.py
from django.urls import path

urlpatterns = [
    # path('', ),
]

unit/urls.py
from django.urls import path

from unit.views import UnitListView, UnitAddView, UnitUpdateView, CaseListView, CaseAddView, CaseUpdateView

app_name = 'unit'

urlpatterns = [
    path('', UnitListView.as_view(), name='list'),
    path('add/', UnitAddView.as_view(), name='add'),
    path('<int:pk>/', UnitUpdateView.as_view(), name='edit'),

    path('box/', CaseListView.as_view(), name='case_list'),
    path('box/add/', CaseAddView.as_view(), name='case_add'),
    path('box/<int:pk>/', CaseUpdateView.as_view(), name='case_edit'),
]

warehouse/urls.py
from django.urls import path

from warehouse.views import *

app_name = 'warehouse'

urlpatterns = [
    path('', WarehouseListView.as_view(), name='list'),
    path('<int:pk>/', WarehouseUpdateView.as_view(), name='edit'),
    path('add/', WarehouseAddView.as_view(), name='add'),

    path('stock/', StockListView.as_view(), name='stock_list'),
    path('stock/<str:details>/', StockListView.as_view(), name='stock_list_details'),

    path('input/', ProductTransactionListView.as_view(), name='stock_input_list'),
    path('input/add/', ProductTransactionAddView.as_view(), name='stock_input_add'),
    path('input/<int:pk>/', ProductTransactionEditView.as_view(), name='stock_input_edit'),

    # path('input/', WarehouseInputListView.as_view(), name='input_list'),
    # path('input/<int:pk>/', WarehouseInputUpdateView.as_view(), name='input_edit'),
    # path('input/add/', WarehouseInputAddView.as_view(), name='input_add'),

    # path('balance/', WarehouseBalanceListView.as_view(), name='balance'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>SmartERP</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
{% include 'navbar.html' %}
<div class="container-fluid">
  {% block content %}

  {% endblock %}
</div>
<hr>
<h6>&nbsp; Copyright © 2014-2020, SmartERP LLC. All rights reserved.</h6>
</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
<script src="{% static 'js/scripts.js' %}"></script>

<script>jQuery(document).ready(function ($) {
    $(".click-row").dblclick(function () {
        window.location = $(this).data("href");
    });

    $(".save_top").click(function () {
        $(".save_bottom").click();
    });

    $('#selectAll').click(function (e) {
        var table = $(e.target).closest('table');
        $('td input:checkbox', table).prop('checked', this.checked);
    });

    $('.group_id').click(e => alert($(e.currentTarget).data('val')));


    {% block dom_ready %}

    {% endblock %}

});
</script>

</html>

templates/navbar_.html
{% load static %}
<style>
    .hello-msg {
        font-size: 18px;
        color: #fff;
        margin-right: 20px;
    }
</style>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'dashboard:dashboard' %}">
        <img src="{% static 'images/logo.png' %}" alt="logo" height="40px;">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {% if request.user.is_staff %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'product:product_list' %}">Products</a>
                </li>
            {% endif %}
        </ul>
    </div>
    <span class="hello-msg">Hello, {{ request.user }}</span>
    <span class="hello-msg"><a href="{% url 'erp_user:logout' %}">&nbsp;Logout</a></span>
</nav>

templates/user/account_settings.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        .profile-pic {
            max-width: 200px;
            max-height: 200px;
            margin: 0 auto;
            border-radius: 50%;
        }
    </style>
    <br>
    <div class="row">
        <div class="col-md-3">
            <div class="card card-body">
                <a class="btn btn-warning" href="{% url 'dashboard:dashboard' %}"> &#8592; Back to Profile</a>
                <hr>
                <h3 style="text-align: center">Account Settings</h3>
                <hr>
                <img class="profile-pic" src="{{ request.user.customer.document.image.url }}" alt="avatar">
            </div>
        </div>
        <div class="col-md-9">
            <div class="card card-body">
                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <input class="btn btn-primary" type="submit" name="Update Information">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #7abecc !important;
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #74cfbf;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: #fff;

        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }
    </style>

</head>
<body>
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">


                <h3 id="form-title">LOGIN</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="username" placeholder="Username..." class="form-control">
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input type="password" name="password" placeholder="Password..." class="form-control">
                    </div>

                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn login_btn" type="submit" value="Login">
                    </div>
                </form>

            </div>
            {% for message in messages %}
                <p id="messages">{{ message }}</p>
            {% endfor %}

            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Don't have an account? <a href="{% url 'erp_user:register' %}" class="ml-2">Sign Up</a>
                </div>

            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/user/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Register</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #7abecc !important;
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #74cfbf;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: #fff;
        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

    </style>

</head>
<body>
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">REGISTER ACCOUNT</h3>
            </div>
            <div class="d-flex justify-content-center form_container">

                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        {{ form.username }}

                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                        </div>
                        {{ form.email }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password1 }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password2 }}
                    </div>

                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn login_btn" type="submit" value="Register Account">
                    </div>
                </form>
            </div>
            {{ form.errors }}
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Already have an account? <a href="{% url 'erp_user:login' %}" class="ml-2">Login</a>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field
*/

    //Query All input fields
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = 'Username..';
    form_fields[2].placeholder = 'Email..';
    form_fields[3].placeholder = 'Enter password...';
    form_fields[4].placeholder = 'Re-enter Password...';


    for (var field in form_fields) {
        form_fields[field].className += ' form-control'
    }
</script>
</body>
</html>

templates/user/user.html
{% extends 'base.html' %}
{% block content %}
    {% include 'order/status.html' %}
    <div class="row">
        <div class="col-md">
            <div class="card card-body">
                <table class="table table-sm">
                    <tr>
                        <th>Product</th>
                        <th>Note</th>
                        <th>Date Ordered</th>
                        <th>Status</th>
                    </tr>
                    {% for order in orders %}
                        <tr>
                            <td>{{ order.items.first.product }}</td>
                            <td>{{ order.note }}</td>
                            <td>{{ order.created_date }}</td>
                            <td>{{ order.status }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}